name: telegram-alert

on:
  workflow_dispatch:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  eth-alert:
    runs-on: ubuntu-latest
    env:
      SYMBOL:            "ETHUSDT"                 # 👈 asset selector
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_CHAT_ID:  ${{ secrets.TELEGRAM_CHAT_ID }}
      LIVE_URL:          ${{ secrets.LIVE_URL }}   # same endpoint, now asset‑aware
      THRESHOLD:         ${{ secrets.THRESHOLD }}
      HTTPS_PROXY:       ${{ secrets.PROXY_URL }}  # optional
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
      - run: npm install
      - run: npm run alert
